security:
  basic:
    enabled: false

  user:
    name: "markus"
    password: "password"


management:
  security:
    enabled: false


logging:
  level:
    io:
      pivotal: "DEBUG"


greeting:
  displayFortune: true

quoteServiceURL: "http://quote-service-dev.cfapps.io/quote"
